const sequelize = require('../config/connection')
const {Recipe} = require('../models')

const recipedata = [
    {
        name: 'Black Truffle Roasted Chicken',
        ingredients: '1 Green Circle Chicken, about 3lbs|5 tablespoons Black Truffle Butter, softened, divided use| ½ Fresh Black Winter Truffle, Fresh Burgundy Truffle, or Fresh Summer Truffle, sliced paper-thin| Kosher salt & freshly ground black pepper',
        direction: 'Preheat oven to 425 degrees F. Remove neck and giblets from the chicken cavity. Pat chicken dry with paper towels.| Using your fingers, carefully pull skin away from breast and leg meat, being careful not to puncture the skin. Insert about 4 tablespoons of black truffle butter evenly under the loosened skin. Insert truffle slices evenly in between the butter and skin. Season inside and out with kosher salt and freshly ground black pepper. Truss chicken with butchers string and fold wings under. Rub remaining tablespoon of butter all over the outside of the chicken.| Place on a rack in a heavy roasting pan. Roast for about 45-60 minutes, basting with pan drippings at the halfway point, until chicken is golden brown and an instant-read thermometer inserted into the thickest part of the meat registers 160 degrees F. (Check halfway through cooking, if the skin over the breast is getting too dark, cover with a small piece of foil until the last 10 minutes.)| Remove chicken from the oven and rest on a cutting board for about 10-15 minutes before carving and serving.',
        description: 'Heres a luxurious twist on a simple roast chicken. Our black truffle butter and fresh black truffle slices are layered under the skin creating an ultra-juicy bird thats full of truffle flavor.'
    },
    {
        name: 'Creamy Pasta with Pancetta & Crispy Mushrooms',
        ingredients: '4 ounces ventrèche or pancetta, cut into ¼” lardons| 3 tablespoons black truffle butter, divided use| 1 package organic chefs mix mushrooms, trimmed and rough chopped| Kosher salt & freshly ground black pepper| 2 shallots, finely chopped| 1 cup chicken stock| 1 pound egg pappardelle| ½ cup heavy cream| 1 teaspoon fresh thyme leaves| Parmigiano Reggiano, for serving, optional',
        direction: 'In a large skillet over medium heat, sauté ventrèche until browned, crisp, and rendered about 8-10 minutes. Remove ventrèche with a slotted spoon, leaving the rendered fat in the pan. Drain ventrèche on a paper towel and set aside.| Raise heat to medium-high and add 1 tablespoon of truffle butter to the pan. Once butter is melted, add mushrooms, turning to coat in the fat. Season with salt and pepper. Sauté until mushrooms have expelled their water and are browned and crisp, about 8-10 minutes. Remove mushrooms to a plate and spread out in an even layer, set aside.| Add another tablespoon of truffle butter to the pan, along with the shallots. Sauté until shallots are translucent, about 3 minutes. Add stock, scraping up any browned bits from the pan. Reduce heat to maintain a simmer and cook until stock is reduced to about 1/3 volume. Reduce heat to low. Remove pan from heat for about a minute then slowly stir in cream. Return to heat and continue to cook, stirring occasionally, until sauce is thickened, about 3 minutes| While the sauce is cooking, cook pasta in a large pot of salted boiling water, until just barely al dente.| Using tongs or a wire spider, transfer pasta to the sauté pan. Add thyme and remaining tablespoon of black truffle butter; toss pasta to coat. Add ½ -1 cup of pasta water, as needed. Add mushrooms and ventrèche, toss to combine. Season to taste with salt and pepper. Serve with cheese on the side.',
        description: 'With plenty of crispy sautéed mushrooms, black truffle butter, and pancetta, this creamy pappardelle is the ultimate comfort food dish.'
    },
    {
        name: 'Wagyu Beef Shepherds Pie',
        ingredients: '4lbs Yukon gold potatoes, peeled and quarted| 1 tablespoon salt, plus more to taste| 1 cup milk, or cream| 5 tablespoons Black Truffle Butter| Freshly cracked black pepper, to taste| ¼ tsp freshly grated nutmeg| 2 lbs ground wagyu beef| 1 large onion, minced| 1 clove garlic, mincd| 2 carrots, diced| 1 cup peas| 1 ½ tbs tomato paste| 2 tsp Dijon| 1 tsp unsweetended cocoa powder| 1/2 container veal demi-glace, dissolved with 1/2 cup hot water| ½ cup red wine',
        direction: 'Place potatoes in a large pot, cover with cold water, add 1 tablespoon salt. Heat over medium-high flame until simmering. Cook until a fork slips in and out easily. Drain potatoes then transfer to the bowl of an electric mixer fitted with the paddle attachment. Mix on medium speed until lumps are gone, about 2 minutes. Add 3 tablespoons black truffle butter, mix until blended. Turn mixer down to low speed. Add cream, salt and pepper to taste, and nutmeg. Do not over mix. Cover with foil, set aside.| Heat a large Dutch-oven or other heavy pot over medium-high flame. Add ground Wagyu beef, cook, breaking up meat with a spoon or spatula until evenly browned and no longer pink. Remove meat with a spotted spoon and set aside. Drain off all but about 2 tablespoons of fat.| Place pot over medium heat. Add onion, garlic and carrot. Cook, stirring up any browned bits from the bottom of the pan, until softened, about 7 minutes. Add beef back to the pot. Add tomato paste, mustard and cocoa powder, mixing well to combine. Stir in peas. Add red wine and demi-glace mixture. Again, stir up any browned bits from the bottom of the pan. Bring to a simmer, turn heat down to low. Maintain simmer until most liquid is evaporated and mixture reaches a thick, saucy consistency, about 20 minutes.| Meanwhile, preheat oven to 425 degrees. Transfer meat mixture to a large baking dish. Spoon mashed potatoes over the top and evenly smooth over the meat using an off-set spatula. Use a fork to make an attractive swirled pattern on the top of the potatoes. Brush with melted truffle butter. Bake until top is golden brown, about 15 – 20 minutes.',
        description: 'This simple shepherds pie recipe puts a luxurious spin on classic comfort food, with rich Wagyu beef and decadent black truffle butter.'
    },
    {
        name: 'Basic Grilled Ribeye Steak',
        ingredients: '2 Angus Beef Ribeye Steaks, or Grass-Fed Ribeye Steaks| Coarse salt| Freshly ground black pepper',
        direction: 'Heat grill to medium-high or heat coals in a charcoal grill until they glow bright orange and ash over.  Lightly oil hot grates.| Let steaks stand at room temperature for about 20 minutes. Season both sides of each steak with coarse salt and freshly cracked black pepper.| Grill steaks for about 6 minutes on the first side, rotating 90 degrees at the halfway mark to create cross-hatch grill marks, if desired. Using tongs, flip each steak to the other side and grill for another 6 minutes, or until desired doneness. We suggest medium-rare, which would register 125 degrees on an instant-read thermometer.| Let steaks rest for 8 -10 minutes before serving.',
        description: 'Heres a basic grilling recipe for perfect ribeye steaks, on either a gas or charcoal grill. Once you have the technique down, experiment with rubs, herbs, sauces, or compound butters'
    },
    {
        name: 'Bison Bleu Cheese Burger',
        ingredients: '4 Bison Burgers| Salt and freshly-ground black pepper, to taste| Porcini Powder, to taste| 4 slices Applewood Smoked Bacon| 6 ounces bleu cheese, such as Roquefort, Point Reyes, or Gorgonzola| 3 tablespoons heavy cream|4 thin slices red onion| 4 slices Jersey tomato, (when in season)| 4 leaves butterhead lettuce, washed and dried| 4 challah rolls| Your favorite burger condiments',
        direction: 'In a large, heavy bottomed skillet over medium flame, cook bacon until crisp. Drain on paper towels, set aside. Pour off all but about 2 tablespoons of the rendered bacon fat. Reheat the skillet over medium-high flame. Season bison patties with salt, pepper and porcini powder on both sides. Make a 2 inch diameter impression in the center of each patty.| Place patties in the pan and cover with a lid or stainless steel bowl. Cook for 6 minutes. Remove lid and carefully flip burgers, continue to cook for 4-5 minutes for medium doneness. Remove burgers and allow to rest on a cutting board.| Crumble blue cheese. Set half of the cheese aside. Put the other half of the cheese into a bowl, add heavy cream and mix gently until combined.| Assemble burgers: place a bottom bun on each plate, then layer ingredients starting with lettuce, tomato and buffalo patty. Top each patty with 2 half slices bacon. Equally spoon blue cheese sauce over bacon, then top with the reserved blue cheese. Add sliced onion and top bun. Serve with duck fat french fries or your favorite potato chips.',
        description: 'Try our big bleu burger recipe, bursting with flavor from meaty ground bison, smokey bacon, and bleu cheese. These burgers are equally good pan-seared or flame-grilled.'
    }
];

const seedRecipes = () => Recipe.bulkCreate(recipedata)
module.exports = seedRecipes